version: '3.9'

services:

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - '9092:9092'
    networks:
      - aic
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
      KAFKA_CFG_MESSAGE_MAX_BYTES: 50000000
      KAFKA_CFG_MAX_REQUEST_SIZE: 50000000
      KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES: 50000000
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 50000000
  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    ports:
      - '9192:9192'
    networks:
      - aic
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:29093,PLAINTEXT_HOST://0.0.0.0:9192'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9192'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
      KAFKA_CFG_MESSAGE_MAX_BYTES: 50000000
      KAFKA_CFG_MAX_REQUEST_SIZE: 50000000
      KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES: 50000000
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 50000000

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - '5433:5432'
    networks:
      - aic
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./init-onfhir-feast-db.sh:/docker-entrypoint-initdb.d/z_init-onfhir-feast-db.sh
      - ./timescaledb:/home/postgres/pgdata/data

networks:
  aic:
    name: aic_net
